sudo: true
language: cpp
env:
  global:
  - GTEST_DIR: ${TRAVIS_BUILD_DIR}/gtest
  - GH_REF: github.com/Openhab-Nodes/libWakaamaEmb.git
  - secure: fNOM2LUil0pumVEIzZ15MNmJUIyyYNPzlDmEpPQms9rG7UbnwC5LkJLKjOrGvrYBqCdBDYEVx/kbev8/RjPn2SivcdNRo4CVVWudr1rF6/Bi+9f+KSisRJbb8UDH91NGheLv3v6fzdTKrYMlMPpFzUONsBWKIf65+UDe8Px+BgL3lWzx3BISyPtSZoGarKmAwOZWVdpDEKeteJzQrPxxLSkdf9p+z0vz7NQR80rPaDcgz4Mh/AwbJl6o+4rQ+XZb8HibTPpfZBX32WAHA9JgBwlxDnHfcdsfcUypxlo+ocp4OM/rd7XqSxxqwHBPTMULDdhmptPdMiZh8U73GxNx9gBrrAgsH6RDpMMjbYhPL7Xq02Czbamg1/LJGmKvOtba9fADZeZEgldz09eWsrIbIDoNg6FB37FiBe4Q1W5s/Bg3uojp9ZoiecyQjcqNTN5osiJpWUj70z0kOm1DXWnPNhhYD2C5iJwAj+YomI1jOAGnhtm2zBmG3NinDTOuVNwC+JTO/TTimo6lAHIccoVhwBj+wRdMVc1dmElbYJA6OxTkj3d3Vhwfj/ODXY7w1CN80KKfbjRwMGbk0Bdh9qpnHYEtKeKEidr6IsY3m0/+RHFOu2yqbo1jv5MjwkV3TsymLqwW4ykuslDtLE/pNkmEYkPy2fKsA+emwwkYz2q0V2g=

matrix:
  include:
  - compiler: gcc
    script: cmake -P update_wakaama.cmake
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - libgtest-dev
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=g++-4.8
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - libgtest-dev
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=g++-4.9
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - libgtest-dev
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=g++-5
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.5
        packages:
        - clang-3.5
        - libgtest-dev
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=clang++-3.5
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        packages:
        - clang-3.6
        - libgtest-dev
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=clang++-3.6
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - libgtest-dev
    env: SCRIPT=cmake CMAKE_CXX_COMPILER=clang++-3.7
  - env: SCRIPT=arduino VERSION=1.6.7 BOARD=arduino:avr:mega:cpu=atmega1280
  - env: SCRIPT=platformio BOARD=megaatmega1280
  - env: SCRIPT=platformio BOARD=esp01
cache:
  directories:
  - "~/.platformio"
script:
  - test/$SCRIPT.sh
